spring:
  application:
    name: "document-revision-service"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: document_revision
  datasource:
    url: jdbc:postgresql://103.142.137.207:5432/dochero-db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://103.142.137.207:5432/dochero-db
    schemas: document_revision
    user: postgres
    password: password
    locations: classpath:db/migration

server:
  error:
    include-stacktrace: never
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://45.119.85.106:40000/eureka
  instance:
    preferIpAddress: true