spring:
  application:
    name: "document-revision-service"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dochero_document_revision
  datasource:
    url: jdbc:postgresql://103.142.137.207:12345/dochero_document_revision
    username: root
    password: 123456
    driverClassName: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://103.142.137.207:12345/dochero_document_revision
    schemas: dochero_document_revision
    user: root
    password: 123456
    locations: classpath:db/migration

server:
  error:
    include-stacktrace: never
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://45.119.85.106:40000/eureka
  instance:
    preferIpAddress: true