spring:
  application:
    name: "document-revision-service"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: document-revision
  datasource:
    url: jdbc:postgresql://localhost:5432/department-db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  cloud:
    discovery:
      enabled: false
  flyway:
    url: jdbc:postgresql://localhost:5432/department-db
    schemas: document-revision
    user: postgres
    password: password
    locations: classpath:db/migration

server:
  error:
    include-stacktrace: never
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka