spring:
  application:
    name: "document-revision-service"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dochero_document_revision
  datasource:
    url: jdbc:postgresql://45.119.85.106:54322/dochero-department
    username: ksharkinc
    password: "ksharkinc2022"
    driverClassName: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://45.119.85.106:54322/dochero-department
    schemas: dochero_document_revision
    user: ksharkinc
    password: "ksharkinc2022"
    locations: classpath:db/migration

server:
  error:
    include-stacktrace: never
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://45.119.85.106:40000/eureka
  instance:
    preferIpAddress: true