# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean -DskipTests=true -B package --file pom.xml

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: phongvanngo/dochero-document-revision-service
          tags: latest
          registry: docker.io
          username: ${{ secrets.NOVAPO_DOCKER_USERNAME }}
          password: ${{ secrets.NOVAPO_DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 103.48.192.223
          username: ${{ secrets.NOVAPO_SERVER_USERNAME }}
          password: ${{ secrets.NOVAPO_SERVER_PASSWORD }}
          script: cd /home/novapo/docker-compose-list/dochero/;git pull;docker stop dochero-document-revision-service;docker rm dochero-document-revision-service; docker pull phongvanngo/dochero-document-revision-service;docker-compose -f document-revision.docker-compose.yml up -d;
